version: '3'

services:
  app:
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    platform: linux/amd64
    env_file: .env
    command: >
      sh -c "alembic upgrade head &&
             uvicorn src.main:fastapi_app --host 0.0.0.0 --port 5000 --reload"
    depends_on:
      db:
        condition: service_healthy
      db_test:
        condition: service_healthy


  db:
    container_name: "db"
    image: postgres:16
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - dev-db:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"
    platform: linux/amd64

  db_test:
    container_name: "db_test"
    image: postgres:16
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_TEST_USER} -d ${POSTGRES_DB_TEST}'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - db_test:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TEST}
      POSTGRES_USER: ${POSTGRES_TEST_USER}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD}
    env_file: .env
    ports:
      - "5433:5432"
    platform: linux/amd64


volumes:
  dev-db:
  db_test: